name: Cl

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Download PageKite
      run: Invoke-WebRequest https://pagekite.net/pk/pagekite.py -OutFile pagekite.py

    - name: Install PageKite Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pagekite

    - name: Setup PageKite
      run: python pagekite.py 3389 rdp.freerdp.pagekite.me $Env:PAGEKITE_SECRET
      env:
        PAGEKITE_SECRET: ${{ secrets.PAGEKITE_SECRET }}

    - name: Enable Terminal Services (RDP)
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

    - name: Enable Remote Desktop Firewall Rules
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Configure RDP User Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Local User Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Create PageKite Tunnel
      run: python pagekite.py 3389 rdp.freerdp.pagekite.me $Env:PAGEKITE_SECRET
      env:
        PAGEKITE_SECRET: ${{ secrets.PAGEKITE_SECRET }}
